"kind": "pipeline"
"name": "heron-deploy"
"node":
  "repo": "Lab3-Spotify-heron"
"steps":
- "image": "plugins/docker"
  "name": "build and push docker image"
  "settings":
    "build_args":
    - "WALRUS_API_BASE_URL=https://walrus.lab3.website"
    - "ENV=staging"
    - "APP_TITLE=Heron"
    "cache_from":
    - "lislab3morris/heron:latest"
    "password":
      "from_secret": "docker-password"
    "repo": "lislab3morris/heron"
    "tags":
    - "latest"
    - "${DRONE_COMMIT_SHA}"
    "username":
      "from_secret": "docker-username"
- "commands":
  - "kubectl set image deployment/heron heron=lislab3morris/heron:${DRONE_COMMIT_SHA} --namespace=heron || exit 1"
  - "kubectl rollout status deployment/heron --namespace=heron || exit 1"
  - "echo Deployment success!"
  "image": "sinlead/drone-kubectl"
  "name": "deploy to k8s"
  "settings":
    "kubernetes_cert":
      "from_secret": "k8s-ca"
    "kubernetes_server":
      "from_secret": "k8s-server"
    "kubernetes_token":
      "from_secret": "k8s-token"
    "namespace": "heron"
    "startTimeout": 240
"trigger":
  "branch":
  - "master"
  "event":
  - "push"
"type": "kubernetes"
